import Head from "next/head";
export default function HeadConfig() {
  return (
    <Head>
      <title className="text-3xl font-bold underline">Personal Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/images/favicon.ico" />
    </Head>
  );
}
